In [1]:
import pandas as pd

In [38]:
year = '2019'
month = 'Feb'
day = '2'

In [39]:
def get_df(month, year, day):
    earnings = pd.read_html('https://www.nasdaq.com/earnings/earnings-calendar.aspx?date=%s-%s-%s'%(year, month, day))
    return earnings[0]

def date_range(month, year, start, delta):
    earnings_df = get_df(month, year, start)
    for i in range(delta-1):
        start = str(int(start) + 1)
        earnings_df = earnings_df.append(get_df(month, year, start))
    return earnings_df

In [40]:
earnings = date_range(month, year, day, 10)

/Users/arturkashperskiy/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/api.py:87: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  result = result.union(other)
/Users/arturkashperskiy/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/api.py:87: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  result = result.union(other)

In [41]:
earnings

,0,1,2,Time,Company Name (Symbol) Market Cap Sort by: Name / Size,Expected Report Date,Fiscal Quarter Ending,Consensus EPS* Forecast,# of Ests,Last Year's Report Date,Last Year's EPS*,% Suprise
0,NASDAQ,7157.23,72.77 ▲ 1.03%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DJIA,24706.35,336.25 ▲ 1.38%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S&P 500,2670.71,34.75 ▲ 1.32%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NASDAQ,7157.23,72.77 ▲ 1.03%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DJIA,24706.35,336.25 ▲ 1.38%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S&P 500,2670.71,34.75 ▲ 1.32%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,"Alexandria Real Estate Equities, Inc. (ARE) Ma...",02/04/2019,Dec 2018,$1.69,4.0,01/29/2018,$1.53,Met
1,NaN,NaN,NaN,NaN,"Alexion Pharmaceuticals, Inc. (ALXN) Market Ca...",02/04/2019,Dec 2018,$1.61,7.0,02/08/2018,$1.28,Met
2,NaN,NaN,NaN,NaN,Alphabet Inc. (GOOGL) Market Cap: $764.4B,02/04/2019,Dec 2018,$11.12,14.0,02/01/2018,$9.7,Met
3,NaN,NaN,NaN,NaN,Apartment Investment and Management Company (A...,02/04/2019,Dec 2018,$0.63,6.0,02/01/2018,$0.63,Met
4,NaN,NaN,NaN,NaN,"AvalonBay Communities, Inc. (AVB) Market Cap: ...",02/04/2019,Dec 2018,$2.32,8.0,01/31/2018,$2.25,Met
5,NaN,NaN,NaN,NaN,"Beazer Homes USA, Inc. (BZH) Market Cap: $389.5M",02/04/2019,Dec 2018,$0.18,1.0,02/06/2018,$0.23,Met
6,NaN,NaN,NaN,NaN,Cabot Corporation (CBT) Market Cap: $2.79B,02/04/2019,Dec 2018,$0.9,3.0,02/06/2018,$0.93,Met
7,NaN,NaN,NaN,NaN,Capital Southwest Corporation (CSWC) Market Ca...,02/04/2019,Dec 2018,$0.36,1.0,02/05/2018,$0.29,Met
8,NaN,NaN,NaN,NaN,Clorox Company (The) (CLX) Market Cap: $19.4B,02/04/2019,Dec 2018,$1.32,7.0,02/02/2018,$1.23,Met
9,NaN,NaN,NaN,NaN,"Gilead Sciences, Inc. (GILD) Market Cap: $88.81B",02/04/2019,Dec 2018,$1.63,8.0,02/06/2018,$1.6,Met
10,NaN,NaN,NaN,NaN,"Hartford Financial Services Group, Inc. (The) ...",02/04/2019,Dec 2018,$0.65,7.0,02/08/2018,$0.81,Met
11,NaN,NaN,NaN,NaN,Kilroy Realty Corporation (KRC) Market Cap: $6...,02/04/2019,Dec 2018,$0.89,6.0,01/31/2018,$0.85,Met
12,NaN,NaN,NaN,NaN,Luminex Corporation (LMNX) Market Cap: $1.17B,02/04/2019,Dec 2018,$0.12,5.0,02/12/2018,$0.17,Met
13,NaN,NaN,NaN,NaN,Olin Corporation (OLN) Market Cap: $3.85B,02/04/2019,Dec 2018,$0.34,6.0,02/06/2018,$0.35,Met
14,NaN,NaN,NaN,NaN,ON Semiconductor Corporation (ON) Market Cap: ...,02/04/2019,Dec 2018,$0.48,11.0,02/02/2018,$0.39,Met
15,NaN,NaN,NaN,NaN,PotlatchDeltic Corporation (PCH) Market Cap: $...,02/04/2019,Dec 2018,$0.04,3.0,01/29/2018,$0.54,Met
16,NaN,NaN,NaN,NaN,Qiagen N.V. (QGEN) Market Cap: $8.29B,02/04/2019,Dec 2018,$0.4,6.0,01/31/2018,$0.43,Met
17,NaN,NaN,NaN,NaN,Regal Beloit Corporation (RBC) Market Cap: $3.22B,02/04/2019,Dec 2018,$1.31,5.0,02/05/2018,$1.14,Met
18,NaN,NaN,NaN,NaN,"Rudolph Technologies, Inc. (RTEC) Market Cap: ...",02/04/2019,Dec 2018,$0.24,4.0,02/01/2018,$0.28,Met
19,NaN,NaN,NaN,NaN,"Saia, Inc. (SAIA) Market Cap: $1.45B",02/04/2019,Dec 2018,$0.88,8.0,02/02/2018,$0.53,Met
20,NaN,NaN,NaN,NaN,Seagate Technology PLC (STX) Market Cap: $11.08B,02/04/2019,Dec 2018,$1.27,7.0,01/29/2018,$1.48,Met
21,NaN,NaN,NaN,NaN,Sysco Corporation (SYY) Market Cap: $32.35B,02/04/2019,Dec 2018,$0.73,5.0,02/05/2018,$0.66,Met
22,NaN,NaN,NaN,NaN,"USA Truck, Inc. (USAK) Market Cap: $145.75M",02/04/2019,Dec 2018,$0.56,2.0,02/01/2018,$0.35,Met
0,NaN,NaN,NaN,NaN,AECOM (ACM) Market Cap: $4.57B,02/05/2019,Dec 2018,$0.52,3.0,02/06/2018,$0.57,Met
...,...,...,...,...,...,...,...,...,...,...,...,...
2,NaN,NaN,NaN,NaN,"Cboe Global Markets, Inc. (CBOE) Market Cap: $...",02/08/2019,Dec 2018,$1.31,6.0,02/09/2018,$0.87,Met
3,NaN,NaN,NaN,NaN,Cleveland-Cliffs Inc. (CLF) Market Cap: $2.7B,02/08/2019,Dec 2018,$0.59,5.0,01/25/2018,$0.26,Met
4,NaN,NaN,NaN,NaN,Coty Inc. (COTY) Market Cap: $5.58B,02/08/2019,Dec 2018,$0.22,8.0,02/08/2018,$0.32,Met
5,NaN,NaN,NaN,NaN,GrafTech International Ltd. (EAF) Market Cap: ...,02/08/2019,Dec 2018,$0.78,1.0,NaN,$n/a,Met
6,NaN,NaN,NaN,NaN,Phillips 66 (PSX) Market Cap: $43.08B,02/08/2019,Dec 2018,$2.34,9.0,02/02/2018,$1.07,Met
7,NaN,NaN,NaN,NaN,Phillips 66 Partners LP (PSXP) Market Cap: $6.03B,02/08/2019,Dec 2018,$1.08,6.0,02/02/2018,$0.83,Met
8,NaN,NaN,NaN,NaN,"Ventas, Inc. (VTR) Market Cap: $21.58B",02/08/2019,Dec 2018,$0.95,10.0,02/09/2018,$1.03,Met
0,NASDAQ,7157.23,72.77 ▲ 1.03%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DJIA,24706.35,336.25 ▲ 1.38%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S&P 500,2670.71,34.75 ▲ 1.32%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NASDAQ,7157.23,72.77 ▲ 1.03%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DJIA,24706.35,336.25 ▲ 1.38%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S&P 500,2670.71,34.75 ▲ 1.32%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,Albany International Corporation (AIN) Market ...,02/11/2019,Dec 2018,$0.63,1.0,02/05/2018,$0.43,Met
1,NaN,NaN,NaN,NaN,"Amber Road, Inc. (AMBR) Market Cap: $229.56M",02/11/2019,Dec 2018,$-0.09,1.0,02/15/2018,$-0.07,Met
2,NaN,NaN,NaN,NaN,Brixmor Property Group Inc. (BRX) Market Cap: ...,02/11/2019,Dec 2018,$0.46,7.0,02/12/2018,$0.52,Met
3,NaN,NaN,NaN,NaN,"Chegg, Inc. (CHGG) Market Cap: $3.84B",02/11/2019,Dec 2018,$0.1,5.0,02/12/2018,$0.06,Met
4,NaN,NaN,NaN,NaN,"Compass Minerals International, Inc. (CMP) Mar...",02/11/2019,Dec 2018,$1.79,2.0,02/13/2018,$1.66,Met
5,NaN,NaN,NaN,NaN,"Elevate Credit, Inc. (ELVT) Market Cap: $203.46M",02/11/2019,Dec 2018,$0.09,2.0,02/08/2018,$0.01,Met
6,NaN,NaN,NaN,NaN,"Everest Re Group, Ltd. (RE) Market Cap: $8.75B",02/11/2019,Dec 2018,$-1.2,4.0,02/05/2018,$13.48,Met
7,NaN,NaN,NaN,NaN,FMC Corporation (FMC) Market Cap: $10.69B,02/11/2019,Dec 2018,$1.39,5.0,02/12/2018,$1.1,Met
8,NaN,NaN,NaN,NaN,Kemper Corporation (KMPR) Market Cap: $4.74B,02/11/2019,Dec 2018,$0.97,3.0,02/13/2018,$0.45,Met
9,NaN,NaN,NaN,NaN,Livent Corporation (LTHM) Market Cap: $1.9B,02/11/2019,Dec 2018,$0.23,1.0,NaN,$n/a,Met
10,NaN,NaN,NaN,NaN,Mercury General Corporation (MCY) Market Cap: ...,02/11/2019,Dec 2018,$0.74,1.0,02/05/2018,$0.15,Met
11,NaN,NaN,NaN,NaN,Mimecast Limited (MIME) Market Cap: $2.06B,02/11/2019,Dec 2018,$0,7.0,02/12/2018,$-0.05,Met
12,NaN,NaN,NaN,NaN,Molina Healthcare Inc (MOH) Market Cap: $8.45B,02/11/2019,Dec 2018,$1.52,10.0,02/12/2018,$0.34,Met
13,NaN,NaN,NaN,NaN,NorthWestern Corporation (NWE) Market Cap: $3.11B,02/11/2019,Dec 2018,$1.06,1.0,02/12/2018,$0.98,Met
14,NaN,NaN,NaN,NaN,"Omega Healthcare Investors, Inc. (OHI) Market ...",02/11/2019,Dec 2018,$0.75,4.0,02/13/2018,$0.79,Met
15,NaN,NaN,NaN,NaN,"Varonis Systems, Inc. (VRNS) Market Cap: $1.5B",02/11/2019,Dec 2018,$0.09,3.0,02/12/2018,$0.18,Met
16,NaN,NaN,NaN,NaN,Vornado Realty Trust (VNO) Market Cap: $12.44B,02/11/2019,Dec 2018,$0.99,9.0,02/12/2018,$0.98,Met

In [42]:
import re
pattern = re.compile(r"\(([A-Z]+)\)")

In [65]:
earnings[earnings.columns[4]].dropna().index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
             7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
           dtype='int64', length=260)

In [54]:
def filter(wow):
    results = pattern.findall(wow)
    if len(results) > 0:
        return results[0]
    else:
        return None

In [55]:
tickers = earnings[earnings.columns[4]].dropna().apply(filter)

In [56]:
tickers

0       ARE
1      ALXN
2     GOOGL
3       AIV
4       AVB
5       BZH
6       CBT
7      CSWC
8       CLX
9      GILD
10      HIG
11      KRC
12     LMNX
13      OLN
14       ON
15      PCH
16     QGEN
17      RBC
18     RTEC
19     SAIA
20      STX
21      SYY
22     USAK
0       ACM
1      AGCO
2      ALLT
3       ALL
4       DOX
5       APU
6       AME
      ...
65      WTS
66       WU
67      YUM
68     ZAYO
0       AVA
1       BEP
2      CBOE
3       CLF
4      COTY
5       EAF
6       PSX
7      PSXP
8       VTR
0       AIN
1      AMBR
2       BRX
3      CHGG
4       CMP
5      ELVT
6        RE
7       FMC
8      KMPR
9      LTHM
10      MCY
11     MIME
12      MOH
13      NWE
14      OHI
15     VRNS
16      VNO
Name: \n\t\t\t\t\t\t                Company Name (Symbol)  Market Cap\n                                        Sort by: Name / Size\n\t\t\t\t\t                , Length: 260, dtype: object

In [57]:
def nasdaq_list():
    df = pd.read_csv('companylist.csv')
    return df

In [58]:
company_list = nasdaq_list()

In [59]:
prices_under_5 = company_list[company_list['LastSale'] < 5]

In [60]:
prices_under_5[prices_under_5['Symbol'].isin(tickers)]

,Symbol,Name,LastSale,MarketCap,IPOyear,Sector,industry,Summary Quote,Unnamed: 8
1384,GPRO,"GoPro, Inc.",4.27,$640.5M,2014.0,Miscellaneous,Industrial Machinery/Components,https://www.nasdaq.com/symbol/gpro,NaN
2101,MOBL,"MobileIron, Inc.",4.42,$466.55M,2014.0,Technology,Computer Software: Prepackaged Software,https://www.nasdaq.com/symbol/mobl,NaN
3423,ZNGA,Zynga Inc.,3.92,$3.38B,2011.0,Technology,EDP Services,https://www.nasdaq.com/symbol/znga,NaN

In [73]:
earnings[earnings.columns.str.contains('GPRO', regex=True)]

ValueError: cannot index with vector containing NA / NaN values